name: Events Demo 1
on: 
  pull_request:
    # Activity Types
    types: 
      # It will only trigger when its opened
      - opened
  workflow_dispatch:
  push:
    # will only triggered by pushing to the following branches
    branches: 
      - master # master
      # reg allowed
      - 'dev-*' # '*' - single char rather than '/' dev-new frv-this-id-new
      - 'feat/**' # '**' - single char including '/' feat/new feat/new/button
      # Ex developer-1 will not trigger
    paths-ignore: # only if we did not change a file into github workflow's folder
      - '.github/workflows/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."